---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-creds
  namespace: default
spec:
  encryptedData:
    password: AgAGIoBR2oC2tuyAZKZN7e7rL9r33Jsc9veTLNBzT3ngqhorPsLy4tt9QWAIHHbQIyZDLnuLuftim18gHhbkRBY7b9qndvskNXSoA7XPahvtiYdY5XvYQLMqW+zVGISG6WdFEbxnuH5sfxKNSs6pVCwSYgXc6WhnR8KF4CMpzpzVkgNobZTG28BP4wwfZGVnrRIy7onafoD2SLDhgYsboPfocCrXH1S+3gBKalaVL6EkC7XmJQif5x7BulgZ/859FwQhX6rQMs55ImbFrbdYVZZzob4P8CZePCyPQO4sUTHmzqN98gYdlh/5p5Zu6NwX3vxYREQ9SFVUg2f5lRECMgm0LUIt2fG6IUkEFr5jNBRx1BwHrOn768XkdbDYVDYFKjwC+kFJsgkLEqUz8HQW4n4b0OZxFDiwrVjOlvYd+H35K+mkCtHA+DzY3TrgzrTc01jj3/xip/7AwCn/U9XdOiswSe9qhuGaMr8xA9RbMIKheQMC6TDQ3Ovjy1NsrxH7cM+q8/T02KqLPrIPg8AMjF9c9+RefcFEqol7Jpcr7lCp7sQ1CuqoBn+LZMTz4qCd7wx1zNPXK/LNI6AQo3TJBcG+lME0bjBEdJNf1duedicRs19jeRYsgTARPxuN/MMDBdK7nUeG9DrTdgUYKF1eVeLYyU6yIdRqg0mXzq9lZFQM2uwZJgRYXOLyeNe9gALIL46psuuPkrY2G5B+3A==
    username: AgAtffs7djIAzC5Z0f4uD1UE4zpP6gdq0ocMwG6+nmvqYlWQq2wTOF/H6a21gTFNNomohtux+lxLOIDkI0QCcLGTA7T232R0WgkyU1kgGugPPAQkxWCerbHMg4Pw2ZZNViyYbnvlfua5jQFr3C/u8GvFOnXra1kcrj+WBsH1TcVVnV93Bq0FZL6+OhNduvTjE2uN6naZro8TRSi8J0rOBkq4NlNw4dlIU32LaDkFHUB6UAu8q5dKxe6mulVQwK1eLrkfDIf2fwQWffAY/K7X7NnsyefS0m7cSMio6QZpEPbBt+Vx/DwlRQyI+aWFzJA2E6FF/2RDjBZl94iQv4dwXggDwObt4KAFs5L/mebGks+Jja2BlrXxKN5hk8vi62om0E9bVfkTrYLjeG/FAUTzAmwvPbQOtEnXazh9Bd3UPwLpOL0f/NYbhRSUso45LUEMRMOamdZWbBsxPxksymdpIfXxsmlxpoxVgUejO9S2O8Ie96y3DPGp4RoYy1rVqXr0SydjnsBiJdjFYAcBmzc3NT+CPfEBfcvQrhob9M8z/vkmh/gNg2UyWuLJ9WVhZ65fbLfq6CFBsEIDMw2xj3qjWIKCpw3JPX5HCatLEQnVjbbrlSDjEhdwdhqvKZZEjzrDzxL8R7eOvv0boMRpsj4KxYrpI94ZvrllLo1kgznhlNu87FOc7XIt8y7wuE9Wwxz2KMLZ6tOLLw==
  template:
    metadata:
      creationTimestamp: null
      name: db-creds
      namespace: default
    type: Opaque
